name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */6 * * *"
  push:
    branches: [main]
    paths:
      - ".github/workflows/run.yml"

jobs:
  version:
    name: Generate Hosts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git config
        run: |
          git config --local user.email "43134606+Ryanjiena@users.noreply.github.com"
          git config --local user.name "Ryanjiena"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Generate
        run: |
          DATE=$(TZ=UTC-8 date '+%Y-%m-%d %H:%M:%S')
          sed -i 's/\r$//' generate_hosts.sh && bash generate_hosts.sh
          if [ "$(git status -sb)" == "## main...origin/main" ];then
            echo -e "\033[42;30m nothing to commit, working tree clean~ \033[0m"
          else
            git status -s && git pull origin main && git commit -S -am "🐳 AutoUpdate ${DATE}" && git push origin main
          fi
